{% set name = "hijri-converter" %}
{% set version = "2.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hijri-converter-{{ version }}.tar.gz
  sha256: db9a5f31c884254163af6a1c39be81c807a5e897ba9587624d6706dd1048f160

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - hijri_converter
    - hijri_converter.locales
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dralshehri/hijri-converter
  summary: Accurate Hijri-Gregorian date converter based on the Umm al-Qura calendar
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - synapticarbors
