{% set name = "hijri-converter" %}
{% set version = "2.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hijri-converter-{{ version }}.tar.gz
  sha256: 7a22438be995f76d7ac78dcd8c5195261615069de2ddbb266aec4ce9c03e06b3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - hijri_converter
    - hijri_converter.locales
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dralshehri/hijri-converter
  summary: Accurate Hijri-Gregorian date converter based on the Umm al-Qura calendar
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - synapticarbors
